### ISSUE TITLE
how could i end the task?

### ISSUE THREAD

**Issue by zzzgit** [idleberg/atom-build-cmd#1]
if i run cmd file by  this plugin in windows OS
after a while could i end this process?
it is a need like "ctrl + C" in cmd.ext

**Comment by idleberg** [comment]
From the [build](https://github.com/noseglid/atom-build) README:

> <kbd>Esc</kbd> terminates build / closes the build window

You could [change](http://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/) that to <kbd>Ctrl</kbd>+<kbd>C</kbd>, but I wouldn't recommend it, since that potentially disables the copy shortcut.
