### ISSUE TITLE
more convenient functionality needed

### ISSUE THREAD

**Issue by zzzgit** [idleberg/atom-build-cmd#2]
hello 
this plugin just simply add a build target to the official plugin "build"
when i need to run a build script,i must open this file and make the tab active first
and then run it vie the "build" plugin 
could i just right click on the file in the tree view,and then simply choose a menu command?

**Comment by idleberg** [comment]
Assuming you keep using the same name for your build batch-files, you can specify custom arguments in the package settings (e.g. `/q /c make.cmd`) and map a key to run that target.

**Comment by zzzgit** [comment]
how to config the "package settings"?

**Comment by idleberg** [comment]
![settings](https://cloud.githubusercontent.com/assets/1504938/20700010/0a5e28ca-b60b-11e6-92b0-a0e96a0d3ad6.png)

See the [Atom Flight Manual](http://flight-manual.atom.io/using-atom/sections/atom-packages/#package-settings) for details
